/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminFinancialRouteImport } from './routes/admin.financial'
import { Route as AdminDemoRouteImport } from './routes/admin.demo'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminAdministratorsRouteImport } from './routes/admin.administrators'
import { Route as AcceptAdminTokenRouteImport } from './routes/accept-admin.$token'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchoolsRouteImport } from './routes/_authenticated/schools'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQuickEvalRouteImport } from './routes/_authenticated/quick-eval'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedExecutiveRouteImport } from './routes/_authenticated/executive'
import { Route as AuthenticatedEvaluationsRouteImport } from './routes/_authenticated/evaluations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AdminClientsIndexRouteImport } from './routes/admin.clients.index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedEvaluationsIndexRouteImport } from './routes/_authenticated/evaluations.index'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes.index'
import { Route as PortalAlunoTokenRouteImport } from './routes/portal.aluno.$token'
import { Route as AdminClientsIdRouteImport } from './routes/admin.clients.$id'
import { Route as AuthenticatedStudentsImportRouteImport } from './routes/_authenticated/students.import'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'
import { Route as AuthenticatedSchoolsIdRouteImport } from './routes/_authenticated/schools.$id'
import { Route as AuthenticatedGroupsIdRouteImport } from './routes/_authenticated/groups.$id'
import { Route as AuthenticatedEvaluationsImportRouteImport } from './routes/_authenticated/evaluations.import'
import { Route as AuthenticatedClassesIdRouteImport } from './routes/_authenticated/classes.$id'
import { Route as AuthenticatedGroupsIdIndexRouteImport } from './routes/_authenticated/groups.$id.index'
import { Route as AuthenticatedClassesIdIndexRouteImport } from './routes/_authenticated/classes.$id.index'
import { Route as AuthenticatedGroupsIdDashboardRouteImport } from './routes/_authenticated/groups.$id.dashboard'
import { Route as AuthenticatedClassesIdDashboardRouteImport } from './routes/_authenticated/classes.$id.dashboard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialRoute = AdminFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemoRoute = AdminDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministratorsRoute = AdminAdministratorsRouteImport.update({
  id: '/administrators',
  path: '/administrators',
  getParentRoute: () => AdminRoute,
} as any)
const AcceptAdminTokenRoute = AcceptAdminTokenRouteImport.update({
  id: '/accept-admin/$token',
  path: '/accept-admin/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolsRoute = AuthenticatedSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuickEvalRoute = AuthenticatedQuickEvalRouteImport.update({
  id: '/quick-eval',
  path: '/quick-eval',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExecutiveRoute = AuthenticatedExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvaluationsRoute =
  AuthenticatedEvaluationsRouteImport.update({
    id: '/evaluations',
    path: '/evaluations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminClientsRoute,
} as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AuthenticatedEvaluationsIndexRoute =
  AuthenticatedEvaluationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEvaluationsRoute,
  } as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassesRoute,
  } as any)
const PortalAlunoTokenRoute = PortalAlunoTokenRouteImport.update({
  id: '/portal/aluno/$token',
  path: '/portal/aluno/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminClientsRoute,
} as any)
const AuthenticatedStudentsImportRoute =
  AuthenticatedStudentsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)
const AuthenticatedSchoolsIdRoute = AuthenticatedSchoolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSchoolsRoute,
} as any)
const AuthenticatedGroupsIdRoute = AuthenticatedGroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedGroupsRoute,
} as any)
const AuthenticatedEvaluationsImportRoute =
  AuthenticatedEvaluationsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedEvaluationsRoute,
  } as any)
const AuthenticatedClassesIdRoute = AuthenticatedClassesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClassesRoute,
} as any)
const AuthenticatedGroupsIdIndexRoute =
  AuthenticatedGroupsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGroupsIdRoute,
  } as any)
const AuthenticatedClassesIdIndexRoute =
  AuthenticatedClassesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassesIdRoute,
  } as any)
const AuthenticatedGroupsIdDashboardRoute =
  AuthenticatedGroupsIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedGroupsIdRoute,
  } as any)
const AuthenticatedClassesIdDashboardRoute =
  AuthenticatedClassesIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedClassesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/classes': typeof AuthenticatedClassesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evaluations': typeof AuthenticatedEvaluationsRouteWithChildren
  '/executive': typeof AuthenticatedExecutiveRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/quick-eval': typeof AuthenticatedQuickEvalRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/schools': typeof AuthenticatedSchoolsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/accept-admin/$token': typeof AcceptAdminTokenRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/classes/$id': typeof AuthenticatedClassesIdRouteWithChildren
  '/evaluations/import': typeof AuthenticatedEvaluationsImportRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRouteWithChildren
  '/schools/$id': typeof AuthenticatedSchoolsIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/students/import': typeof AuthenticatedStudentsImportRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/portal/aluno/$token': typeof PortalAlunoTokenRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/evaluations/': typeof AuthenticatedEvaluationsIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/classes/$id/dashboard': typeof AuthenticatedClassesIdDashboardRoute
  '/groups/$id/dashboard': typeof AuthenticatedGroupsIdDashboardRoute
  '/classes/$id/': typeof AuthenticatedClassesIdIndexRoute
  '/groups/$id/': typeof AuthenticatedGroupsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/executive': typeof AuthenticatedExecutiveRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/quick-eval': typeof AuthenticatedQuickEvalRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/schools': typeof AuthenticatedSchoolsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/accept-admin/$token': typeof AcceptAdminTokenRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/blog': typeof BlogIndexRoute
  '/evaluations/import': typeof AuthenticatedEvaluationsImportRoute
  '/schools/$id': typeof AuthenticatedSchoolsIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/students/import': typeof AuthenticatedStudentsImportRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/portal/aluno/$token': typeof PortalAlunoTokenRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/evaluations': typeof AuthenticatedEvaluationsIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/classes/$id/dashboard': typeof AuthenticatedClassesIdDashboardRoute
  '/groups/$id/dashboard': typeof AuthenticatedGroupsIdDashboardRoute
  '/classes/$id': typeof AuthenticatedClassesIdIndexRoute
  '/groups/$id': typeof AuthenticatedGroupsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evaluations': typeof AuthenticatedEvaluationsRouteWithChildren
  '/_authenticated/executive': typeof AuthenticatedExecutiveRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/quick-eval': typeof AuthenticatedQuickEvalRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/_authenticated/schools': typeof AuthenticatedSchoolsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/accept-admin/$token': typeof AcceptAdminTokenRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/classes/$id': typeof AuthenticatedClassesIdRouteWithChildren
  '/_authenticated/evaluations/import': typeof AuthenticatedEvaluationsImportRoute
  '/_authenticated/groups/$id': typeof AuthenticatedGroupsIdRouteWithChildren
  '/_authenticated/schools/$id': typeof AuthenticatedSchoolsIdRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/students/import': typeof AuthenticatedStudentsImportRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/portal/aluno/$token': typeof PortalAlunoTokenRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/evaluations/': typeof AuthenticatedEvaluationsIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/_authenticated/classes/$id/dashboard': typeof AuthenticatedClassesIdDashboardRoute
  '/_authenticated/groups/$id/dashboard': typeof AuthenticatedGroupsIdDashboardRoute
  '/_authenticated/classes/$id/': typeof AuthenticatedClassesIdIndexRoute
  '/_authenticated/groups/$id/': typeof AuthenticatedGroupsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/classes'
    | '/dashboard'
    | '/evaluations'
    | '/executive'
    | '/groups'
    | '/knowledge'
    | '/quick-eval'
    | '/reports'
    | '/risk'
    | '/schools'
    | '/settings'
    | '/students'
    | '/team'
    | '/accept-admin/$token'
    | '/admin/administrators'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/demo'
    | '/admin/financial'
    | '/admin/logs'
    | '/admin/monitoring'
    | '/admin/support'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/blog/$slug'
    | '/invite/$token'
    | '/p/$slug'
    | '/admin/'
    | '/auth/'
    | '/blog/'
    | '/classes/$id'
    | '/evaluations/import'
    | '/groups/$id'
    | '/schools/$id'
    | '/students/$id'
    | '/students/import'
    | '/admin/clients/$id'
    | '/portal/aluno/$token'
    | '/classes/'
    | '/evaluations/'
    | '/groups/'
    | '/students/'
    | '/admin/clients/'
    | '/classes/$id/dashboard'
    | '/groups/$id/dashboard'
    | '/classes/$id/'
    | '/groups/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/executive'
    | '/knowledge'
    | '/quick-eval'
    | '/reports'
    | '/risk'
    | '/schools'
    | '/settings'
    | '/team'
    | '/accept-admin/$token'
    | '/admin/administrators'
    | '/admin/dashboard'
    | '/admin/demo'
    | '/admin/financial'
    | '/admin/logs'
    | '/admin/monitoring'
    | '/admin/support'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/blog/$slug'
    | '/invite/$token'
    | '/p/$slug'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/evaluations/import'
    | '/schools/$id'
    | '/students/$id'
    | '/students/import'
    | '/admin/clients/$id'
    | '/portal/aluno/$token'
    | '/classes'
    | '/evaluations'
    | '/groups'
    | '/students'
    | '/admin/clients'
    | '/classes/$id/dashboard'
    | '/groups/$id/dashboard'
    | '/classes/$id'
    | '/groups/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/classes'
    | '/_authenticated/dashboard'
    | '/_authenticated/evaluations'
    | '/_authenticated/executive'
    | '/_authenticated/groups'
    | '/_authenticated/knowledge'
    | '/_authenticated/quick-eval'
    | '/_authenticated/reports'
    | '/_authenticated/risk'
    | '/_authenticated/schools'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/team'
    | '/accept-admin/$token'
    | '/admin/administrators'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/demo'
    | '/admin/financial'
    | '/admin/logs'
    | '/admin/monitoring'
    | '/admin/support'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/blog/$slug'
    | '/invite/$token'
    | '/p/$slug'
    | '/admin/'
    | '/auth/'
    | '/blog/'
    | '/_authenticated/classes/$id'
    | '/_authenticated/evaluations/import'
    | '/_authenticated/groups/$id'
    | '/_authenticated/schools/$id'
    | '/_authenticated/students/$id'
    | '/_authenticated/students/import'
    | '/admin/clients/$id'
    | '/portal/aluno/$token'
    | '/_authenticated/classes/'
    | '/_authenticated/evaluations/'
    | '/_authenticated/groups/'
    | '/_authenticated/students/'
    | '/admin/clients/'
    | '/_authenticated/classes/$id/dashboard'
    | '/_authenticated/groups/$id/dashboard'
    | '/_authenticated/classes/$id/'
    | '/_authenticated/groups/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AcceptAdminTokenRoute: typeof AcceptAdminTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PSlugRoute: typeof PSlugRoute
  PortalAlunoTokenRoute: typeof PortalAlunoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financial': {
      id: '/admin/financial'
      path: '/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AdminFinancialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demo': {
      id: '/admin/demo'
      path: '/demo'
      fullPath: '/admin/demo'
      preLoaderRoute: typeof AdminDemoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administrators': {
      id: '/admin/administrators'
      path: '/administrators'
      fullPath: '/admin/administrators'
      preLoaderRoute: typeof AdminAdministratorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accept-admin/$token': {
      id: '/accept-admin/$token'
      path: '/accept-admin/$token'
      fullPath: '/accept-admin/$token'
      preLoaderRoute: typeof AcceptAdminTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools': {
      id: '/_authenticated/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-eval': {
      id: '/_authenticated/quick-eval'
      path: '/quick-eval'
      fullPath: '/quick-eval'
      preLoaderRoute: typeof AuthenticatedQuickEvalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executive': {
      id: '/_authenticated/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof AuthenticatedExecutiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluations': {
      id: '/_authenticated/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof AuthenticatedEvaluationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/evaluations/': {
      id: '/_authenticated/evaluations/'
      path: '/'
      fullPath: '/evaluations/'
      preLoaderRoute: typeof AuthenticatedEvaluationsIndexRouteImport
      parentRoute: typeof AuthenticatedEvaluationsRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedClassesRoute
    }
    '/portal/aluno/$token': {
      id: '/portal/aluno/$token'
      path: '/portal/aluno/$token'
      fullPath: '/portal/aluno/$token'
      preLoaderRoute: typeof PortalAlunoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/_authenticated/students/import': {
      id: '/_authenticated/students/import'
      path: '/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof AuthenticatedStudentsImportRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/schools/$id': {
      id: '/_authenticated/schools/$id'
      path: '/$id'
      fullPath: '/schools/$id'
      preLoaderRoute: typeof AuthenticatedSchoolsIdRouteImport
      parentRoute: typeof AuthenticatedSchoolsRoute
    }
    '/_authenticated/groups/$id': {
      id: '/_authenticated/groups/$id'
      path: '/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AuthenticatedGroupsIdRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/evaluations/import': {
      id: '/_authenticated/evaluations/import'
      path: '/import'
      fullPath: '/evaluations/import'
      preLoaderRoute: typeof AuthenticatedEvaluationsImportRouteImport
      parentRoute: typeof AuthenticatedEvaluationsRoute
    }
    '/_authenticated/classes/$id': {
      id: '/_authenticated/classes/$id'
      path: '/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof AuthenticatedClassesIdRouteImport
      parentRoute: typeof AuthenticatedClassesRoute
    }
    '/_authenticated/groups/$id/': {
      id: '/_authenticated/groups/$id/'
      path: '/'
      fullPath: '/groups/$id/'
      preLoaderRoute: typeof AuthenticatedGroupsIdIndexRouteImport
      parentRoute: typeof AuthenticatedGroupsIdRoute
    }
    '/_authenticated/classes/$id/': {
      id: '/_authenticated/classes/$id/'
      path: '/'
      fullPath: '/classes/$id/'
      preLoaderRoute: typeof AuthenticatedClassesIdIndexRouteImport
      parentRoute: typeof AuthenticatedClassesIdRoute
    }
    '/_authenticated/groups/$id/dashboard': {
      id: '/_authenticated/groups/$id/dashboard'
      path: '/dashboard'
      fullPath: '/groups/$id/dashboard'
      preLoaderRoute: typeof AuthenticatedGroupsIdDashboardRouteImport
      parentRoute: typeof AuthenticatedGroupsIdRoute
    }
    '/_authenticated/classes/$id/dashboard': {
      id: '/_authenticated/classes/$id/dashboard'
      path: '/dashboard'
      fullPath: '/classes/$id/dashboard'
      preLoaderRoute: typeof AuthenticatedClassesIdDashboardRouteImport
      parentRoute: typeof AuthenticatedClassesIdRoute
    }
  }
}

interface AuthenticatedClassesIdRouteChildren {
  AuthenticatedClassesIdDashboardRoute: typeof AuthenticatedClassesIdDashboardRoute
  AuthenticatedClassesIdIndexRoute: typeof AuthenticatedClassesIdIndexRoute
}

const AuthenticatedClassesIdRouteChildren: AuthenticatedClassesIdRouteChildren =
  {
    AuthenticatedClassesIdDashboardRoute: AuthenticatedClassesIdDashboardRoute,
    AuthenticatedClassesIdIndexRoute: AuthenticatedClassesIdIndexRoute,
  }

const AuthenticatedClassesIdRouteWithChildren =
  AuthenticatedClassesIdRoute._addFileChildren(
    AuthenticatedClassesIdRouteChildren,
  )

interface AuthenticatedClassesRouteChildren {
  AuthenticatedClassesIdRoute: typeof AuthenticatedClassesIdRouteWithChildren
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
}

const AuthenticatedClassesRouteChildren: AuthenticatedClassesRouteChildren = {
  AuthenticatedClassesIdRoute: AuthenticatedClassesIdRouteWithChildren,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
}

const AuthenticatedClassesRouteWithChildren =
  AuthenticatedClassesRoute._addFileChildren(AuthenticatedClassesRouteChildren)

interface AuthenticatedEvaluationsRouteChildren {
  AuthenticatedEvaluationsImportRoute: typeof AuthenticatedEvaluationsImportRoute
  AuthenticatedEvaluationsIndexRoute: typeof AuthenticatedEvaluationsIndexRoute
}

const AuthenticatedEvaluationsRouteChildren: AuthenticatedEvaluationsRouteChildren =
  {
    AuthenticatedEvaluationsImportRoute: AuthenticatedEvaluationsImportRoute,
    AuthenticatedEvaluationsIndexRoute: AuthenticatedEvaluationsIndexRoute,
  }

const AuthenticatedEvaluationsRouteWithChildren =
  AuthenticatedEvaluationsRoute._addFileChildren(
    AuthenticatedEvaluationsRouteChildren,
  )

interface AuthenticatedGroupsIdRouteChildren {
  AuthenticatedGroupsIdDashboardRoute: typeof AuthenticatedGroupsIdDashboardRoute
  AuthenticatedGroupsIdIndexRoute: typeof AuthenticatedGroupsIdIndexRoute
}

const AuthenticatedGroupsIdRouteChildren: AuthenticatedGroupsIdRouteChildren = {
  AuthenticatedGroupsIdDashboardRoute: AuthenticatedGroupsIdDashboardRoute,
  AuthenticatedGroupsIdIndexRoute: AuthenticatedGroupsIdIndexRoute,
}

const AuthenticatedGroupsIdRouteWithChildren =
  AuthenticatedGroupsIdRoute._addFileChildren(
    AuthenticatedGroupsIdRouteChildren,
  )

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsIdRoute: typeof AuthenticatedGroupsIdRouteWithChildren
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsIdRoute: AuthenticatedGroupsIdRouteWithChildren,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedSchoolsRouteChildren {
  AuthenticatedSchoolsIdRoute: typeof AuthenticatedSchoolsIdRoute
}

const AuthenticatedSchoolsRouteChildren: AuthenticatedSchoolsRouteChildren = {
  AuthenticatedSchoolsIdRoute: AuthenticatedSchoolsIdRoute,
}

const AuthenticatedSchoolsRouteWithChildren =
  AuthenticatedSchoolsRoute._addFileChildren(AuthenticatedSchoolsRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedStudentsImportRoute: typeof AuthenticatedStudentsImportRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedStudentsImportRoute: AuthenticatedStudentsImportRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvaluationsRoute: typeof AuthenticatedEvaluationsRouteWithChildren
  AuthenticatedExecutiveRoute: typeof AuthenticatedExecutiveRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedQuickEvalRoute: typeof AuthenticatedQuickEvalRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
  AuthenticatedSchoolsRoute: typeof AuthenticatedSchoolsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClassesRoute: AuthenticatedClassesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvaluationsRoute: AuthenticatedEvaluationsRouteWithChildren,
  AuthenticatedExecutiveRoute: AuthenticatedExecutiveRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedQuickEvalRoute: AuthenticatedQuickEvalRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
  AuthenticatedSchoolsRoute: AuthenticatedSchoolsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminClientsRouteChildren {
  AdminClientsIdRoute: typeof AdminClientsIdRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
}

const AdminClientsRouteChildren: AdminClientsRouteChildren = {
  AdminClientsIdRoute: AdminClientsIdRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
}

const AdminClientsRouteWithChildren = AdminClientsRoute._addFileChildren(
  AdminClientsRouteChildren,
)

interface AdminRouteChildren {
  AdminAdministratorsRoute: typeof AdminAdministratorsRoute
  AdminClientsRoute: typeof AdminClientsRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDemoRoute: typeof AdminDemoRoute
  AdminFinancialRoute: typeof AdminFinancialRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministratorsRoute: AdminAdministratorsRoute,
  AdminClientsRoute: AdminClientsRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDemoRoute: AdminDemoRoute,
  AdminFinancialRoute: AdminFinancialRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AcceptAdminTokenRoute: AcceptAdminTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  PSlugRoute: PSlugRoute,
  PortalAlunoTokenRoute: PortalAlunoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
