GRANT EXECUTE ON FUNCTION public.is_platform_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_super_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_admin_role(uuid, public.admin_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_tenant_role(uuid, public.member_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_tenant_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_tenant_member(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_write_tenant(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tenant_can_add_student(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_tenant_with_owner(text, public.tenant_type) TO authenticated;
GRANT EXECUTE ON FUNCTION public.accept_invitation(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.accept_admin_invitation(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.impersonate_tenant(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.end_impersonation() TO authenticated;
GRANT EXECUTE ON FUNCTION public.portal_set_enabled(uuid, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.portal_regenerate_token(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_demo_tenant() TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_demo_environment() TO authenticated;
GRANT EXECUTE ON FUNCTION public.restore_demo_environment() TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_demo_environment() TO authenticated;
GRANT EXECUTE ON FUNCTION public.class_stats(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.group_stats(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.school_stats(uuid) TO authenticated;